//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspirantesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aspirante
    {
        public long Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public int Id_Ciudad_Nacimiento { get; set; }
        public int Id_Grupo_Sanguineo { get; set; }
        public int Id_Tipo_Documento { get; set; }
        public string Numero_Documento { get; set; }
        public System.DateTime Fecha_Expedicion { get; set; }
        public int Id_Ciudad_Expedicion { get; set; }
        public int Id_Genero { get; set; }
        public int Id_Estado_Civil { get; set; }
        public string Numero_Telefono { get; set; }
        public string Numero_Celular { get; set; }
        public string Foto { get; set; }
        public long Id_Inscripcion { get; set; }
        public bool Completo { get; set; }
    
        public virtual Estado_Civil Estado_Civil { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Grupo_Sanguineo Grupo_Sanguineo { get; set; }
        public virtual Inscripcion Inscripcion { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Municipio Municipio1 { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
    }
}
