//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspirantesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inscripcion()
        {
            this.Aspirante = new HashSet<Aspirante>();
        }
    
        public long Id { get; set; }
        public int Id_Tipo_Aspirante { get; set; }
        public int Id_Modalidad { get; set; }
        public int Id_Sede { get; set; }
        public int Id_Programa { get; set; }
        public int Id_Periodo { get; set; }
        public int Id_Estado_Inscripcion { get; set; }
        public long Id_Usuario { get; set; }
        public bool Completo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aspirante> Aspirante { get; set; }
        public virtual Estado_Inscripcion Estado_Inscripcion { get; set; }
        public virtual Modalidad Modalidad { get; set; }
        public virtual Periodo_Academico Periodo_Academico { get; set; }
        public virtual Programa_Academico Programa_Academico { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Tipo_Aspirante Tipo_Aspirante { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
