//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspirantesApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UAMDBEntities : DbContext
    {
        public UAMDBEntities()
            : base("name=UAMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aspirante> Aspirante { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Estado_Civil> Estado_Civil { get; set; }
        public virtual DbSet<Estado_Inscripcion> Estado_Inscripcion { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Grupo_Sanguineo> Grupo_Sanguineo { get; set; }
        public virtual DbSet<Inscripcion> Inscripcion { get; set; }
        public virtual DbSet<Modalidad> Modalidad { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Periodo_Academico> Periodo_Academico { get; set; }
        public virtual DbSet<Programa_Academico> Programa_Academico { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Tipo_Aspirante> Tipo_Aspirante { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
